server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: lingo-admin # 路由规则id，自定义，唯一
          uri: lb://lingo-admin # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/** # 这里是以请求路径作为判断规则
        - id: lingo-user
          uri: lb://lingo-user
          predicates:
            - Path=/user/**
        - id: lingo-video
          uri: lb://lingo-video
          predicates:
            - Path=/video/**,/home/**
        - id: lingo-oss
          uri: lb://lingo-oss
          predicates:
            - Path=/oss/**
        - id: lingo-search
          uri: lb://lingo-search
          predicates:
            - Path=/search/**
        - id: lingo-vocabulary
          uri: lb://lingo-vocabulary
          predicates:
            - Path=/vocabulary/**
lingo:
  tube:
    jwt:
      location: classpath:jwt.jks # 秘钥地址
      alias: jwt # 秘钥别名
      password: lingotube # 秘钥文件密码
      tokenTTL: 30m # 登录有效期
    auth:
      excludePaths: # 无需登录校验的路径
        - /swagger-ui/
        - /swagger-resources/**
        - /**/v2/api-docs
        - /**/*.html
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.jpg
        - /**/*.mp4
        - /user/verifyCode
        - /user/register
        - /user/login
        - /user/reset/password
        - /admin/**
        - /home/**
        - /video/**
        - /search/**
logging:
  level:
    root: info
    com.moncoder.lingo: debug


